name: clubbers
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  geolocator: ^6.1.14
  google_maps_flutter: ^1.1.1
  get: ^3.24.0
  shared_preferences: ^0.5.12+4
  sticky_infinite_list: ^3.0.1
  sliding_up_panel: ^1.0.2
  dotted_line: ^2.0.2
  cached_network_image: ^2.3.3
  google_fonts: ^1.1.1
  flutter_icons:
  flutter_svg: ^0.19.1
  flutter:
    sdk: flutter
  

dev_dependencies:
  mockito: ^4.1.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - lib/assets/svg/
    - lib/assets/img/
    - lib/assets/map_style.json

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
